EcomShoes-Webshop/EcomShoes-Webshop/Controllers/ManageProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EcomShoes_Webshop.Models;
using System.Transactions;

namespace EcomShoes_Webshop.Controllers
{
    public class ManageProductsController : Controller
    {
        private K23T3aEntities db = new K23T3aEntities();
        // GET: /ManageProducts/
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category);
            return View(products.ToList());
        }
        public ActionResult Image(string id)
        {
            var path = Server.MapPath("~/Content/Images"); // đường dẫn chứa tệp hình ảnh của sản phẩm
            path = System.IO.Path.Combine(path, id); // tên hình ảnh là id của mã sản phẩm
            return File(path, "image/*");
        }
        //Kiểm tra mã sản phẩm đã tồn tại trong database: Nhung, Tú
        private void checkProductCodeCreate(Product model) {
            // x.ProductCode: giá trị trong database; model.ProductCode: giá trị trong view
            var isProductCodeExist = db.Products.Any(x => x.ProductCode == model.ProductCode);//kiểm tra sự tồn tại
            if (isProductCodeExist) {
                ModelState.AddModelError("ProductCode", RangBuoc.codeProduct_Exist);
            }
        }
        private void checkProductCodeEdit(Product model)
        {
            var isProductCodeExist = db.Products.Any(x => x.ProductCode == model.ProductCode && x.ID != model.ID);
            if (isProductCodeExist)
            {
                ModelState.AddModelError("ProductCode", RangBuoc.codeProduct_Exist);
            }
        }
        private void checkQuantityAndStatus(Product model) {
            if (model.Quantity>0 && model.Status=="DEACTIVE") {
                ModelState.AddModelError("Status", RangBuoc.deactive_Product);

            }
            else if (model.Quantity <= 0 && model.Status == "ACTIVE") {
                ModelState.AddModelError("Status",RangBuoc.active_Product);
            }
        }
        private void checkProductCode(Product model)
        {
            if (model.ProductCode.Length < 2 && model.ProductCode.Length > 15)
            {
                ModelState.AddModelError("Status","Vui lòng nhập lại đúng định dạng");
            }

            
        }
        // GET: /ManageProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            
            if (product == null)
            {
                return HttpNotFound();
            }
 
            return View(product);
        }

        // GET: /ManageProducts/Create
        public ActionResult Create()
        {
     
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "NameCategory");
            //Tạo viewbag hiển thị giá trị mặc định cho Status
            var statusItems = new[]
            {
                new { Id = "DEACTIVE", Name = "Hết hàng" },
                new { Id = "ACTIVE", Name = "Còn hàng" },
            };
            ViewBag.Status = new SelectList(statusItems, "Id", "Name");
            return View();
        }

        // POST: /ManageProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product)
        {
            checkProductCode(product);
            checkPrice(product); //Kiểm tra giá trị giá gốc và giá bán phải lớn hơn 0.
            checkProductCodeCreate(product); //Kiểm tra mã sản phẩm đã tồn tại hay chưa.
            checkQuantityAndStatus(product); //Kiểm tra mốc số lượng và tình trạng
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    //thêm model vào database
                    product.CreatedDate = DateTime.Now;
                    product.UpdateDate = DateTime.Now;
                    db.Products.Add(product);
                    db.SaveChanges();

                    //gán hình vào file app_data

                    var path = Server.MapPath("~/Content/Images");
                    path = System.IO.Path.Combine(path, product.ID.ToString()); //file ảnh sản phẩm sẽ có tên là id của sẩn phẩm.
                    Request.Files["Image"].SaveAs(path);
                    product.ImageURL = path; //ImageURL sẽ lưu đường dẫn tới file ảnh.

                    //All done successfully       
                    db.SaveChanges();
                    scope.Complete();
                    return RedirectToAction("Index");

                }
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "NameCategory", product.CategoryID);
            var statusItems = new[]
            {
                new { Id = "DEACTIVE", Name = "Hết hàng" },
                new { Id = "ACTIVE", Name = "Còn hàng" },
            };
            ViewBag.Status = new SelectList(statusItems, "Id", "Name");

            return View(product);
        }
        private void checkPrice(Product model)
        {
            if (model.SalePrice <= 0 && model.OriginalPrice <= 0)
            {
                ModelState.AddModelError("SalePrice", RangBuoc.price_Less_0);
                ModelState.AddModelError("OriginalPrice", RangBuoc.price_Less_0);
            }
        }

        // GET: /ManageProducts/Edit/5
        public ActionResult Edit(int id)
        {
            var statusItems = new[]
            {
                new { Id = "DEACTIVE", Name = "Hết hàng" },
                new { Id = "ACTIVE", Name = "Còn hàng" },
            };
            ViewBag.Status = new SelectList(statusItems, "Id", "Name");
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "NameCategory", product.CategoryID);
            return View(product);
        }

        // POST: /ManageProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product)
        {
            checkPrice(product);
            checkProductCodeEdit(product);
            checkQuantityAndStatus(product);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    //save edit of product
                    product.UpdateDate = DateTime.Now;
                    db.Entry(product).State = EntityState.Modified;

                    db.SaveChanges();
                    //add file to app_data
                    var path = Server.MapPath("~/Content/Images");
                    path = System.IO.Path.Combine(path, product.ID.ToString());
                    if (Request.Files["Image"].ContentLength != 0)
                    {
                        Request.Files["Image"].SaveAs(path);
                    }
                    product.ImageURL = path; //gán đường dẫn vào ImageURL
                    //All done successfully
                    db.SaveChanges(); // save lại đường dẫn
                    scope.Complete();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "NameCategory", product.CategoryID);
            var statusItems = new[]
            {
                new { Id = "DEACTIVE", Name = "Hết hàng" },
                new { Id = "ACTIVE", Name = "Còn hàng" },
            };
            ViewBag.Status = new SelectList(statusItems, "Id", "Name");
            return View(product);
        }

        // GET: /ManageProducts/Delete/5
        public ActionResult Delete(int id)
        {
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: /ManageProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            var inOrder = db.OrderDetails.Where(x => x.ProductID == id);
            if (inOrder.Count() != 0)
            {
                TempData["msg"] = "<script>alert('Sản phẩm hiện tại đang tồn tại trong giỏ hàng!!! Vui lòng thực hiện sau khi sản phẩm này không còn có trong đơn hàng nào.');</script>";
               
            }
            else
            {
                db.Products.Remove(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EcomShoes-Webshop/EcomShoes-Webshop/Views/ManageProducts/Create.cshtml
@model EcomShoes_Webshop.Models.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<section class="panel">
    <header class="panel-heading">
        Tạo mới sản phẩm
    </header>
    <div class="panel-body">
        @using (Html.BeginForm("Create", "ManageProducts", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.CategoryID, "Danh mục", htmlAttributes: new { @class = "control-label col-lg-2 col-sm-2" })
                    <div class="col-sm-10">
                        @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = " form-control" })
                        @Html.ValidationMessageFor(model => model.CategoryID)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductCode, "Mã sản phẩm", htmlAttributes: new { @class = "control-label col-lg-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.ProductCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ProductCode, "", new { @class = "text-danger" }) <!-- Cảnh báo bắt buộc nhập-->
                       
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductName, "Tên sản phẩm", htmlAttributes: new { @class = "control-label col-lg-2 col-sm-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })  <!-- Cảnh báo bắt buộc nhập-->
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SalePrice, "Giá bán", htmlAttributes: new { @class = "control-label col-lg-2 col-sm-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.SalePrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SalePrice, "", new { @class = "text-danger" })  <!-- Cảnh báo bắt buộc nhập-->
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.OriginalPrice, "Giá gốc", htmlAttributes: new { @class = "control-label col-lg-2 col-sm-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.OriginalPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.OriginalPrice, "", new { @class = "text-danger" })  <!-- Cảnh báo bắt buộc nhập-->
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-lg-2 col-sm-2" })
                    <div class="col-lg-10">
                        @Html.DropDownListFor(model => model.Status, null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Status)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Quantity, "Số lượng", htmlAttributes: new { @class = "control-label col-lg-2 col-sm-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Quantity)  <!-- Cảnh báo bắt buộc nhập-->
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-lg-2 col-sm-2" })
                    <div class="col-lg-10">
                        @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })  <!-- Cảnh báo bắt buộc nhập-->
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, "Mô tả sản phẩm", htmlAttributes: new { @class = "control-label col-lg-2 col-sm-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } }) 
                    </div>
                </div>


                <div class="form-group">
                    <label for="1339" class="control-label col-md-2">Hình ảnh sản phẩm</label>
                    <div class="col-md-10">
                        <input type="file" name="Image" id="1339" onchange="readIMG(this)" />
                        <img id="Demo" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                        <input type="submit" value="Lưu" class="btn btn-danger" />
                    </div>
                </div>

            </div>
        }
    </div>

    <div class="panel-heading">
        @Html.ActionLink("Quay lại", "Index", null, htmlAttributes: new { @class = "btn btn-info" })
    </div>

</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readIMG(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#Demo')
                        .attr('src', e.target.result)
                        .width(150)
                        .height(200);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

EcomShoes-Webshop/EcomShoes-Webshop/Views/ManageProducts/Delete.cshtml
@model EcomShoes_Webshop.Models.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@*<h2>Xóa sản phẩm</h2>

<h3>Bạn có chắc muốn xóa sản phẩm này?</h3>
<div>
    <h4> CHI TIẾT SẢN PHẨM</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            Mã sản phẩm
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductCode)
        </dd>
        <dt>
            Tên sản phẩm
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt>
            Giá bán
        </dt>
        <dd>
            @Model.SalePrice.ToString("N0") VNĐ
        </dd>
        <dt>
            Giá gốc
        </dt>
        <dd>
            @Model.OriginalPrice.ToString("N0") VNĐ
        </dd>
        <dt>
            Hình ảnh sản phẩm
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImageURL)
        </dd>
        <dt>
            Ngày tạo
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt>
            Ngày cập nhật
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
        <dt>
            Mô tả sản phẩm
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            Số lượng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>
        <dt>
            Danh mục
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.NameCategory)
        </dd>
            @Html.Raw(TempData["msg"])

    </dl>
    
        

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" /> |
            @Html.ActionLink("Trở về", "Index")
        </div>
    }
</div>*@
<section class="panel">
    <header class="panel-heading">
        Chi tiết sản phẩm
    </header>
    <div class="panel-body">
        @using (Html.BeginForm("Delete", "ManageProducts"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <div class="form-group">
                    <label for="1339" class="control-label col-md-2">Hình ảnh</label>
                    <td>
                        <img src="@Url.Action("Image", new { id = Model.ID})" style="width: 300px" class="img-thumbnail" />
                    </td>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CategoryID, "Danh mục", htmlAttributes: new { @class = "control-label col-lg-2 col-sm-2" })
                    <div class="col-sm-10">
                        @Html.DisplayFor(model => model.Category.NameCategory)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductCode, "Mã sản phẩm", htmlAttributes: new { @class = "control-label col-lg-2" })
                    <div class="col-sm-10">
                        @Html.DisplayFor(model => model.ProductCode)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductName, "Tên sản phẩm", htmlAttributes: new { @class = "control-label col-lg-2 col-sm-2" })
                    <div class="col-sm-10">
                        @Html.DisplayFor(model => model.ProductName)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SalePrice, "Giá bán", htmlAttributes: new { @class = "control-label col-lg-2 col-sm-2" })
                    <div class="col-sm-10">
                        @Html.DisplayFor(model => model.SalePrice)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.OriginalPrice, "Giá gốc", htmlAttributes: new { @class = "control-label col-lg-2 col-sm-2" })
                    <div class="col-sm-10">
                        @Html.DisplayFor(model => model.OriginalPrice)
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.CreatedDate, "Ngày khởi tạo", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.CreatedDate)
                    </div>
                </div>
                @Html.Raw(TempData["msg"])
            </div>
                <div class="panel-heading">
            <input type="submit" value="Xóa" class="btn btn-danger" /> |
            @Html.ActionLink("Quay lại", "Index", null, htmlAttributes: new { @class = "btn btn-info" })
    </div>
        }
    </div>



</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readIMG(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#Demo')
                        .attr('src', e.target.result)
                        .width(150)
                        .height(200);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

EcomShoes-Webshop/EcomShoes-Webshop/Views/ManageProducts/Details.cshtml
@model EcomShoes_Webshop.Models.Product

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@*<h2>Details</h2>

<div>
    <h4>Product</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductCode)
        </dt>

        <dd>
            @Html.EditorFor(model => model.ProductCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.EditorFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SalePrice)
        </dt>

        <dd>
            @Html.EditorFor(model => model.SalePrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OriginalPrice)
        </dt>

        <dd>
            @Html.EditorFor(model => model.OriginalPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            @Html.EditorFor(model => model.ImageURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.EditorFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.EditorFor(model => model.UpdateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.EditorFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.EditorFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.EditorFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.EditorFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.NameCategory)
        </dt>

        <dd>
            @Html.EditorFor(model => model.Category.NameCategory)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@
<section class="panel">
    <header class="panel-heading">
        Thông tin sản phẩm
    </header>
    <div class="panel-body">
        @using (Html.BeginForm("Details", "ManageProducts"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <div class="form-group">
                    <label for="1339" class="control-label col-md-2">Hình ảnh</label>
                    <td>
                        <img src="@Url.Action("Image", new { id = Model.ID})" style="width: 300px" class="img-thumbnail" />
                    </td>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CategoryID, "Danh mục", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.Category.NameCategory, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductCode, "Mã sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.ProductCode, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductName, "Tên sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SalePrice, "Giá bán", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.SalePrice, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.OriginalPrice, "Giá gốc", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.OriginalPrice, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Quantity, "Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Description, "Mô tả sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-lg-10">
                     @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-lg-10">
                  @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UpdateDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UpdateDate, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
                    </div>
                </div>

            </div>
        }
    </div>

    <div class="panel-heading">
        @Html.ActionLink("Quay lại", "Index", null, htmlAttributes: new { @class = "btn btn-info" })
    </div>

</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readIMG(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#Demo')
                        .attr('src', e.target.result)
                        .width(150)
                        .height(200);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}