EcomShoes-Webshop/EcomShoes-Webshop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EcomShoes_Webshop.Models;
namespace EcomShoes_Webshop.Controllers
{
    public class HomeController : Controller
    {
        private K23T3aEntities db = new K23T3aEntities();
        public ActionResult Index()
        {
            return View(db.Products.ToList());

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Search(string text)
        {
            var itemsz = db.Products.Where(x => x.ProductName.ToLower().Contains(text.ToLower())).ToList();

            if (itemsz.Count() > 0)
            {
                //ViewBag.Message = "";
            }
            else
            {
                ViewBag.Message = "No Item found";

            }
            ViewData["Item"] = itemsz;
            return View(itemsz);
        }
    }
}

EcomShoes-Webshop/EcomShoes-Webshop/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EcomShoes_Webshop.Models;

namespace EcomShoes_Webshop.Controllers
{
    public class productsController : Controller
    {
        private K23T3aEntities db = new K23T3aEntities();
        //
        // GET: /products/
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }
        public ViewResult product_detail(int ID = 0)
        {
            // Tra về đôi tượng với điều kiện
            Product product = db.Products.SingleOrDefault(n => n.ID == ID);
            if (product == null)
            {
                // Trả về trang báo lỗi
                Response.StatusCode = 404;
                return null;
            }
            return View(product);
        }
	}
}

EcomShoes-Webshop/EcomShoes-Webshop/Views/Home/Index.cshtml
@using EcomShoes_Webshop.Models;
@model List<Product>
@{
    ViewBag.Title = "Home Page";
}
<style>
    #imgProduct {
        /* height: 200px; */
        /* width: 200px; */
        /* display: inherit; */
        /* position: relative; */
        /* float: left; */
        width: 200px;
        height: 200px;
        background-position: 50% 50%;
        background-repeat: no-repeat;
        background-size: cover;
    }
    #imgPro{
        width:100%;
    }
    .col-md-4.product-men {
        height: 332px;
    }
</style>
<div class="ads-grid_shop">
    <div class="shop_inner_inf">
        <!-- tittle heading -->
        <!-- //tittle heading -->
        <!-- product left -->
        <div class="side-bar col-md-3">
            <div class="search-hotel">
                <h3 class="agileits-sear-head">Search Here..</h3>
                <form action="@Url.Action("Search", "Home")" method="post">
                    <input type="search" placeholder="Product name..." name="text" required="">
                    <input type="submit" value=" ">
                </form>
            </div>
          
            <!-- deals -->
            
            <!-- //deals -->

        </div>
        <!-- //product left -->
        <!-- product right -->
        <div class="left-ads-display col-md-9">
            <div class="wrapper_top_shop">
                <div class="col-md-6 shop_left">
                    <img src="/Content/images/banner3.jpg" alt="">
                    <h6>40% off</h6>
                </div>
                <div class="col-md-6 shop_right">
                    <img src="/Content/images/banner2.jpg" alt="">
                    <h6>50% off</h6>
                </div>
                <div class="clearfix"></div>
                <!-- product-sec1 -->
                <div class="product-sec1">
                    <!--/mens-->
                    @foreach (var item in Model)
                    {
                        <div class="col-md-4 product-men">
                        <div class="product-shoe-info shoe">
                            <div class="men-pro-item">
                                <div class="men-thumb-item" id="imgPro">
                                    <img id="imgProduct" src="@Url.Content("~/manageProducts/Image/"+item.ID)" alt="" >
                                    <div class="men-cart-pro">
                                        <div class="inner-men-cart-pro">
                                            <a href="@Url.Action("product_detail","products", new { @ID = @item.ID})" class="link-product-add-cart">Quick View</a>
                                        </div>
                                    </div>
                                    <span class="product-new-top">New</span>
                                </div>
                                <div class="item-info-product">
                                    <h4>
                                        <a href="@Url.Action("product_detail","products", new { @ID = @item.ID})">@item.ProductName </a>
                                    </h4>
                                    <div class="info-product-price">
                                        <div class="grid_meta">
                                            <div class="product_price">
                                                <div class="grid-price ">
                                                    <span class="money ">@String.Format("{0:0,0}", item.OriginalPrice) ₫</span> 
                                                </div>
                                            </div>
                                            <ul class="stars">
                                                <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
                                                <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
                                                <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
                                                <li><a href="#"><i class="fa fa-star-half-o" aria-hidden="true"></i></a></li>
                                                <li><a href="#"><i class="fa fa-star-o" aria-hidden="true"></i></a></li>
                                            </ul>
                                        </div>
                                
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    }
                    
                    <!-- //mens -->
                    <div class="clearfix"></div>

                </div>

                <!-- //product-sec1 -->
                <div class="col-md-6 shop_left shp">
                    <img src="/Content/images/banner4.jpg" alt="">
                    <h6>21% off</h6>
                </div>
                <div class="col-md-6 shop_right shp">
                    <img src="/Content/images/banner1.jpg" alt="">
                    <h6>31% off</h6>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

EcomShoes-Webshop/EcomShoes-Webshop/Views/Home/Search.cshtml
@{
    ViewBag.Title = "Search";
}
<style>
    #imgProduct {
        /* height: 200px; */
        /* width: 200px; */
        /* display: inherit; */
        /* position: relative; */
        /* float: left; */
        width: 200px;
        height: 200px;
        background-position: 50% 50%;
        background-repeat: no-repeat;
        background-size: cover;
    }

    #imgPro {
        width: 100%;
    }

    .col-md-4.product-men {
        height: 332px;
    }
</style>
<h2>Search</h2>
<div class="product-sec1">
    <!--/mens-->
    @foreach (var item in ViewData["Item"] as IList<EcomShoes_Webshop.Models.Product>)
    {
        <div class="col-md-4 product-men">
            <div class="product-shoe-info shoe">
                <div class="men-pro-item">
                    <div class="men-thumb-item">
                        <img id="imgProduct" src="@Url.Content("~/manageProducts/Image/"+item.ID)" alt="">
                        <div class="men-cart-pro">
                            <div class="inner-men-cart-pro">
                                <a href="@Url.Action("product_detail","products", new { @ID = @item.ID})" class="link-product-add-cart">Quick View</a>
                            </div>
                        </div>
                        <span class="product-new-top">New</span>
                    </div>
                    <div class="item-info-product">
                        <h4>
                            <a href="@Url.Action("product_detail","products", new { @ID = @item.ID})">@item.ProductName </a>
                        </h4>
                        <div class="info-product-price">
                            <div class="grid_meta">
                                <div class="product_price">
                                    <div class="grid-price ">
                                        <span class="money ">@String.Format("{0:0,0}", item.OriginalPrice) ₫</span>
                                    </div>
                                </div>
                                <ul class="stars">
                                    <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-star-half-o" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-star-o" aria-hidden="true"></i></a></li>
                                </ul>
                            </div>
                            <div class="shoe single-item hvr-outline-out">
                                <form action="#" method="post">
                                    <input type="hidden" name="cmd" value="_cart">
                                    <input type="hidden" name="add" value="1">
                                    <input type="hidden" name="shoe_item" value="Bella Toes">
                                    <input type="hidden" name="amount" value="675.00">
                                    <button type="submit" class="shoe-cart pshoe-cart"><i class="fa fa-cart-plus" aria-hidden="true"></i></button>

                                    <a href="#" data-toggle="modal" data-target="#myModal1"></a>
                                </form>

                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    }

    <!-- //mens -->
    <div class="clearfix"></div>

</div>