EcomShoes-Webshop/EcomShoes-Webshop/Models/OrderDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcomShoes_Webshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}

EcomShoes-Webshop/EcomShoes-Webshop/Controllers/ManageOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EcomShoes_Webshop.Models;

namespace EcomShoes_Webshop.Controllers
{
    public class ManageOrdersController : Controller
    {
        private K23T3aEntities db = new K23T3aEntities();

        public List<Cart> GetCart()
        {
            List<Cart> listCart = Session["Giohang"] as List<Cart>;
            if(listCart == null)
            {
                listCart = new List<Cart>();
                Session["Giohang"] = listCart;
            }
            return listCart;
        }

        // GET: /ManageOrders/
        public ActionResult Index()
        {
            return View(db.Orders.ToList());
        }
        public ActionResult Image(string id)
        {
            var path = Server.MapPath("~/App_Data"); // đường dẫn chứa tệp hình ảnh của sản phẩm
            path = System.IO.Path.Combine(path, id); // tên hình ảnh là id của mã sản phẩm
            return File(path, "image/*");
        }

        public ActionResult Edit(int? id)
        {
            var statusItems = new[]
            {
                new { Id = "0", Name = "Đang chờ xác nhận" },
                new { Id = "1", Name = "Đã nhận" },
                new { Id = "2", Name = "Đang xử lý và đóng gói "},
                new { Id = "3", Name = "Đang trên đường giao hàng" },
                new { Id = "4", Name = "Đã nhận hàng" }
            };
            ViewBag.Status = new SelectList(statusItems, "Id", "Name");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

         //POST: /ManageOrders/Edit/5
         //To protect from overposting attacks, please enable the specific properties you want to bind to, for 
         //more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
             var statusItems = new[]
            {
                new { Id = "0", Name = "Đang chờ xác nhận" },
                new { Id = "1", Name = "Đã nhận" },
                new { Id = "2", Name = "Đang xử lý và đóng gói "},
                new { Id = "3", Name = "Đang trên đường giao hàng" },
                new { Id = "4", Name = "Đã nhận hàng" }
            };
        }

        // GET: /ManageOrders/Delete/5
        public ActionResult Delete(int? code)
        {
            if (code == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(code);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: /ManageOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int code)
        {
            Order order = db.Orders.Find(code);
            OrderDetail orderdetail = db.OrderDetails.Find(code);
            db.Orders.Remove(order);
            db.OrderDetails.Remove(orderdetail);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult OrderDetails(int id)
        {
                var  orderdetail = db.OrderDetails.Find(id);          
                return View(orderdetail);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Order order)
        {
            if (ModelState.IsValid)
            {           
                List<Cart> cart = GetCart();
                order.CreatedDate = DateTime.Now;
                order.Status = 0;
                db.Orders.Add(order);
                foreach(var item in cart)
                {
                    OrderDetail orderdetail = new OrderDetail();
                    orderdetail.OrderID = order.id;
                    orderdetail.ProductID = item.iMaSP;
                    orderdetail.Quantity = (int)item.isoLuong;
                    orderdetail.Price = Convert.ToDecimal(item.thanhTien);
                    db.OrderDetails.Add(orderdetail);
                    order.TotalPrice += Convert.ToDecimal(item.thanhTien);
                    db.Orders.Add(order);
                    Product product = db.Products.Find(item.iMaSP);
                    product.Quantity = product.Quantity - item.isoLuong;
                    db.Entry(product).State = EntityState.Modified;
                }
                db.SaveChanges();
                Session["Giohang"] = null;
                return RedirectToAction("Index", "Home");
            }
            return View("~/Views/ManageOrders/Create.cshtml");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EcomShoes-Webshop/EcomShoes-Webshop/Views/ManageOrders/Create.cshtml
@model EcomShoes_Webshop.Models.Order

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "ManageOrders")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.OrderCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderCode)
                @Html.ValidationMessageFor(model => model.OrderCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate)
                @Html.ValidationMessageFor(model => model.CreatedDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactName)
                @Html.ValidationMessageFor(model => model.ContactName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactAddress, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactAddress)
                @Html.ValidationMessageFor(model => model.ContactAddress)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactPhone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactPhone)
                @Html.ValidationMessageFor(model => model.ContactPhone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactEmail, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactEmail)
                @Html.ValidationMessageFor(model => model.ContactEmail)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactReceiverName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactReceiverName)
                @Html.ValidationMessageFor(model => model.ContactReceiverName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactReceiverAddress, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactReceiverAddress)
                @Html.ValidationMessageFor(model => model.ContactReceiverAddress)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactReceiverPhone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactReceiverPhone)
                @Html.ValidationMessageFor(model => model.ContactReceiverPhone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactReceiverEmail, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactReceiverEmail)
                @Html.ValidationMessageFor(model => model.ContactReceiverEmail)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note)
                @Html.ValidationMessageFor(model => model.Note)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeName)
                @Html.ValidationMessageFor(model => model.EmployeeName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status)
                @Html.ValidationMessageFor(model => model.Status)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalPrice, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalPrice)
                @Html.ValidationMessageFor(model => model.TotalPrice)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EcomShoes-Webshop/EcomShoes-Webshop/Views/ManageOrders/Delete.cshtml
@model EcomShoes_Webshop.Models.Order

@{
    ViewBag.Title = "Hủy đơn hàng";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Hủy đơn hàng</h2>

<h3>Bạn có chắc là muốn hủy đơn hàng này?</h3>
<div>
    <h4>Đơn hàng</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Ngày đặt hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
           Tên người đặt hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactName)
        </dd>

        <dt>
            Địa chỉ người đặt hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactAddress)
        </dd>

        <dt>
           Số điện thoại người đặt hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactPhone)
        </dd>

        <dt>
            Email người đặt hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactEmail)
        </dd>

        <dt>
           Tên người nhận
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactReceiverName)
        </dd>

        <dt>
            Địa chỉ người nhận
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactReceiverAddress)
        </dd>

        <dt>
            Số điện thoại người nhận
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactReceiverPhone)
        </dd>

        <dt>
           Email người nhận
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactReceiverEmail)
        </dd>

        <dt>
            Ghi chú
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            Mã đơn hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderCode)
        </dd>

        <dt>
           Trạng thái đơn hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
           Tên nhân viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeName)
        </dd>

        <dt>
            Tổng cộng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Hủy đơn hàng" class="btn btn-default" /> |
            @Html.ActionLink("Trở lại", "Index")
        </div>
    }
</div>

EcomShoes-Webshop/EcomShoes-Webshop/Views/ManageOrders/Edit.cshtml
@model EcomShoes_Webshop.Models.Order

@{
    ViewBag.Title = "Chỉnh sửa đơn hàng";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chỉnh sửa đơn hàng</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Đơn hàng</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)


    <div class="form-group">
        @Html.LabelFor(model => model.OrderCode,"Mã đơn hàng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrderCode, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrderCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CreatedDate,"Ngày tạo đơn hàng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContactName,"Tên người đặt hàng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContactName, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContactName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContactAddress,"Địa chỉ người đặt hàng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContactAddress, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContactAddress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContactPhone,"Số điện thoại người đặt hàng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContactPhone, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContactPhone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContactEmail,"Email người đặt hàng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContactEmail, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContactEmail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContactReceiverName,"Tên người nhận", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContactReceiverName, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContactReceiverName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContactReceiverAddress,"Địa chỉ người nhận", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContactReceiverAddress, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContactReceiverAddress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContactReceiverPhone,"Số điện thoại người nhận", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContactReceiverPhone, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContactReceiverPhone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContactReceiverEmail,"Email người nhận", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContactReceiverEmail, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContactReceiverEmail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Note,"Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmployeeName,"Tên nhân viên", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EmployeeName, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Status,"Trạng thái đơn hàng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Status, null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EcomShoes-Webshop/EcomShoes-Webshop/Views/ManageOrders/Index.cshtml
@model IEnumerable<EcomShoes_Webshop.Models.Order>

@{
    ViewBag.Title = "Quản lý đơn hàng";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<section class="panel">
    <header class="panel-heading">
        Đơn đặt hàng
    </header>
    <div class="panel-body">
        <div class="adv-table editable-table ">
            <div class="space15"></div>
            <table class="table table-striped table-hover table-bordered" id="editable-sample">
                <thead>
                    <tr>
                        <th>
                            Ngày đặt hàng
                        </th>
                        <th>
                            Mã đơn hàng
                        </th>
                        <th>
                            Trạng thái đơn hàng
                        </th>
                        <th>
                            Tên khách hàng
                        </th>
                        <th>
                            Điện thoại
                        </th>
                        <th>
                            Email
                        </th>
                        <th>Chỉnh sửa</th>
                        <th>Chi tiết</th>
                        <th>Xóa</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.CreatedDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OrderCode)
                            </td>
                            <td>
                                @switch (item.Status)
                                {
                                    case 0:
                                        <text>Đang chờ xác nhận</text>
                                        break;
                                    case 1:
                                        <text>Đã nhận</text>
                                        break;
                                    case 2:
                                        <text>Đang xử lý và đóng gói</text>
                                        break;
                                    case 3:
                                     <text>Đang trên đường giao hàng </text>
                                        break;
                                    case 4:
                                        <text>Đã nhận hàng</text>
                                        break;
                                    default:
                                        <text>Đang chờ xác nhận</text>
                                        break;
                                }
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ContactName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ContactPhone)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ContactEmail)
                            </td>
                            <td>
                                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.id }, htmlAttributes: new { @class = "btn btn-primary btn-xs" })
                            </td>
                            <td>
                                @Html.ActionLink("Chi tiết", "OrderDetails", new { id = item.id}, htmlAttributes: new { @class = "btn btn-primary btn-xs" })
                            </td>
                            <td>
                                @if (item.Status == 0 || item.Status == 1)
                                {
                                @Html.ActionLink("Xóa", "Delete", new { code = item.id }, htmlAttributes: new { @class = "btn btn-danger btn-xs" })
                                }
                                else {
                                @Html.ActionLink(" ","Delete", new { code = item.id }, htmlAttributes: new { @class = "linkdisabled" })
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>